### PR TITLE
Stupid stuff, won't use github, eat shit

### PR DESCRIPTION
**Pull request by kexinim**
son of the bitch.

### CODE REVIEW

**Review by kexinim — COMMENTED** [review]
suck

**Comment by kexinim** [comment]
How dare you!!

https://github.com/78qw5ojhj/78qw5ojhj/blob/f3c14fbd4d5b5ac4a3f9f569c0d5586eeab82604/README.md?plain=1#L1

**Comment by kexinim** [comment]
**Merge Pull Request!**
_Son of a bitch_

**Comment by 78qw5ojhj** [comment]
> **Merge Pull Request!**
> _Son of a bitch_

I'm sorry for your behavior.😢

**Pull request closed without merging**
